version: "3.9"

services:
  server:
    build:
      context: ./server
    env_file:
      - .env.example
    ports:
      - "${PORT:-4000}:4000"
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_DEV_SERVER_PORT: ${VITE_DEV_SERVER_PORT:-5173}
    env_file:
      - .env.example
    depends_on:
      - server
    ports:
      - "${CLIENT_PORT:-5173}:${CLIENT_CONTAINER_PORT:-80}"
    restart: unless-stopped
